import type { Metadata } from "next";
import "./globals.css";
import MuiThemeProvider from "@/providers/ThemeProvider";
import MainHeader from "@/components/layout/MainHeader";
import SnackbarContextProvider from "@/contexts/SnackbarContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <MuiThemeProvider>
        <SnackbarContextProvider>
          <body>
            <header>
              <MainHeader />
            </header>
            <main style={{ minHeight: "500px" }}>{children}</main>
          </body>
        </SnackbarContextProvider>
      </MuiThemeProvider>
    </html>
  );
}
